name: Pre Release

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  dockerImage: 'ghcr.io/galexrt/fivemanage-lite'

jobs:
  release_nightly:
    #if: github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # Docker stuff
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: master
          MAJOR_STRING_TOKEN: "BREAKING*CHANGE|*#major*"
          MINOR_STRING_TOKEN: "*feat*|*#minor*"
          PATCH_STRING_TOKEN: "*fix*|*chore*|*docs*|*update*|#patch|*tweak*"
          DEFAULT_BRANCH: develop
          PRERELEASE: true

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.dockerImage }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      # more docker stuff
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./build/package/Dockerfile
          platforms: linux/amd64,linux/arm64
          sbom: true
          push: true
          provenance: mode=max
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: |
            ${{ env.dockerImage }}:${{ steps.tag.outputs.new_tag }}
            ${{ env.dockerImage }}:latest
          build-args: |
            LITE_VERSION=${{ steps.tag.outputs.new_tag }}

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          name: 'Nightly Release ${{ steps.tag.outputs.new_tag }}'
          tag: ${{ steps.tag.outputs.new_tag }}
          version: ${{ steps.tag.outputs.new_tag }}
          prerelease: true
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
